### PR TITLE
Feature/ci linting

### PR DESCRIPTION
**Pull request by dmcollom**
I've never set up linting for TravisCI before, so hopefully this is the preferred way to do so.

Also included are fixes for the million files that didn't pass the style checks.

### CODE REVIEW

**Comment by dmcollom** [comment]
I included it as a dependency so that contributors can easily run it locally, but I will instead make a note of what to install/run before PRing in the docs.

**Comment by Fingel** [comment]
I'd rather leave it up to each contributor. There are many tools that do the job. For example, I use flake8. Pycodestyle is probably the most basic one.

**Comment by dmcollom** [comment]
Well on that note, should we instead use a more full-featured linter? I chose pycodestyle because it's what Astropy uses, but I'm open to something a bit more robust.

**Comment by Fingel** [comment]
I think pycodestyle is fine. Flake8 is the same thing with a little extra, not really a big deal.

**Pull request merged**
