### PR TITLE
Added useful links to LCO facility form.

### PR DESCRIPTION
**Pull request by cvalenzu**
We needed a easy access to the LCO's Exposure Time Calculator so we added the links to the form similar to https://observe.lco.global/create/ 

image

Also we added the `ipp_value` min, max value constraint described in the LCO obervation portal.

### CODE REVIEW

**Comment by cvalenzu** [comment]
Hi, im trying to fix the merge conflicts

In

**Comment by cvalenzu** [comment]
Sorry, I closed this PR accidentally.

Now the merge conflicts are fixed, but the period and jitter fields are only showing on imaging tab.

**Comment by dmcollom** [comment]
Hi Camilo,

I'm sorry, I saw the merge conflicts but decided I would address them in a few days. I should have mentioned something! Thanks for working on it--I'll take a look this morning.

**Comment by dmcollom** [comment]
Camilo,

I just took a look, and you don't need to worry--it looks like period and jitter were missing from the spectroscopy form in dev (which is actually an oversight!). Your merge resolution was just fine, and I'll merge it and make the fix to ensure period and jitter are available on both forms. Thanks so much for your contribution!

**Pull request merged**
