### PR TITLE
Adding settings for JPEGs into .tmpl

### PR DESCRIPTION
**Pull request by zemogle**

### CODE REVIEW

**Comment by Fingel** [comment]
I think the reason there are conflict is because master was merged in manually. You should only branch/merge development (master will be merged into development).

**Comment by zemogle** [comment]
This was done because `development` had lagged behind `master`, I think due to the observing portal v3 upgrade.

**Comment by Fingel** [comment]
I did this manually in this commit: https://github.com/TOMToolkit/tom_base/commit/f064ac8c1d92a464b35e87f7db79f608586878ea 
Does that negate the need for this PR?
Also, this will break people upgrading their TOMs regardless. Code should not assume these settings exist, but should instead use try/except blocks and use sensible defaults if the settings do not exist.

**Comment by zemogle** [comment]
That's perfect. Thanks.

**Comment by zemogle** [comment]
I just noticed that you did this commit on `master` only. Could you pull it into `development`? thanks.

**Pull request closed without merging**
