### PR TITLE
Add mag error and nondetections to mars and plot

### PR DESCRIPTION
**Pull request by Fingel**
This PR implements a few things:

1. Adds support for importing magnitude error from MARS lightcurves.
2. Adds support for importing non detections from MARS lightcurves.
3. Implements plotting both of the above on the photometry for target
   plot.
4. Fixes photometry being saved under the wrong filter.

I hope you will consider mergint this, as by default the photometry plot
is missing quite a bit of useful data.

image

### CODE REVIEW

**Comment by dmcollom** [comment]
I'm happy to merge it, as I agree that it's very necessary, but the tests will need to be passing first.

**Comment by Fingel** [comment]
OK cool, I fixed the tests. Admittedly I didn't run them, the suite takes so long to run. Is it making network requests or something?

**Comment by dmcollom** [comment]
Well, I discovered yesterday that's there's at least one test for a view that makes a network call (#486 ), but there are canary tests that run when you run a simple `./manage.py test`. The way to exclude those is with `./manage.py test --exclude-tag=canary`, which is now appropriately documented [here](https://github.com/TOMToolkit/tom_base/blob/main/README-dev.md#run-tests).

**Review by dmcollom — APPROVED** [review]

**Comment by Fingel** [comment]
Oh nice, I'll run without the canary tests next time.

**Pull request merged**
