### PR TITLE
remove SOARFacility.get_facility_status inheritance

### PR DESCRIPTION
**Pull request by griffin-h**
Right now the "facility status" tab on the target page lists every LCO site twice. This is because the `SOARFacility` inherits its `get_facility_status` method from `LCOFacility`, which gets the status of every LCO site from the scheduler. This fix just removes that inheritance so that each LCO site is only listed once (from `LCOFacility.get_facility_status`).

### CODE REVIEW

**Review by jchate6 — CHANGES_REQUESTED** [review]
I'm not a fan of this change. I think it makes more sense to update the LCO facility to only include sites listed in the facility.

I'll work on making some commits that accomplish this.

**Comment by griffin-h** [comment]
Just to clarify, SOAR is *not* listed in the LCO facility status API. (Why this is is a separate question.) So I don't think it makes sense for the `SOARFacility` to query that API at all. On the other hand, all the sites included in that API *do* belong to the `LCOFacility`, so no checking is needed there unless that changes.

**Comment by jchate6** [comment]
> Just to clarify, SOAR is _not_ listed in the LCO facility status API. (Why this is is a separate question.) So I don't think it makes sense for the `SOARFacility` to query that API at all. On the other hand, all the sites included in that API _do_ belong to the `LCOFacility`, so no checking is needed there unless that changes.

So, this doesn't seem to be true. Querying `https://observe.lco.global/api/telescope_states/` returns 
```    "sor.doma.4m0a": [
        {
            "telescope": "sor.doma.4m0a",
            "event_type": "AVAILABLE",
            "event_reason": "Available for scheduling",
            "start": "2022-09-21T18:30:42Z",
            "end": "2022-09-21T18:30:42Z"
        }
    ],
```
However, the `SOR` site is NOT listed in `LCOFacility.sites` and shouldn't be included in the base call unless `sites` is otherwise defined.

I believe the changes I made address this and accomplish the ultimate goal of this PR to keep things from repeating in the observatory status list.

**Comment by jchate6** [comment]
@griffin-h If you want to have a chat about this PR, just let me know.

**Comment by griffin-h** [comment]
> So, this doesn't seem to be true. Querying `https://observe.lco.global/api/telescope_states/` returns
> 
> ```
>         {
>             "telescope": "sor.doma.4m0a",
>             "event_type": "AVAILABLE",
>             "event_reason": "Available for scheduling",
>             "start": "2022-09-21T18:30:42Z",
>             "end": "2022-09-21T18:30:42Z"
>         }
>     ],
> ```
> 
> However, the `SOR` site is NOT listed in `LCOFacility.sites` and shouldn't be included in the base call unless `sites` is otherwise defined.
> 
> I believe the changes I made address this and accomplish the ultimate goal of this PR to keep things from repeating in the observatory status list.

Hah, this was literally not true yesterday, and I just asked @cmccully about it. Maybe it's only listed on AEON nights (like tonight)?  Anyway I agree that your changes are better!

**Pull request merged**
